version: "3.7"
services:
  db:
    image: postgres:12
    container_name: db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=dbname
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    depends_on:
      - db
    volumes:
    - ./pgadmin:/var/lib/pgadmin
    ports:
      - "5555:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: kushal2017328@gmail.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin
volumes:
  db_data: